### ISSUE TITLE
[Enhancement] Support for create expense group.

### ISSUE THREAD

**Issue by samta** [namaggarwal/splitwise#10]
I have added support for creating an expense group. If this feature looks good, I can submit the code.

**Comment by namaggarwal** [comment]
Hi,

Please submit a Pull Request.

Naman

**Comment by samta** [comment]
Will do, thanks.

**Comment by samta** [comment]
Hi,
Created a pull request, would you mind reviewing it.

**Comment by namaggarwal** [comment]
Hi 

I am reviewing it

Naman

**Comment by samta** [comment]
Hi, Can you pls review the suggested changes.

Thanks,
Samta

**Comment by namaggarwal** [comment]
Please look at the comment at the PR

**Comment by samta** [comment]
Addressed the review comments, pls take a look.

**Comment by namaggarwal** [comment]
Hi,

I have merged your pull request. Thanks for the good work. I will release a new version soon.

Naman
