### ISSUE TITLE
getExpenses() returning deleted expenses

### ISSUE THREAD

**Issue by salehraghib** [namaggarwal/splitwise#18]
It seems like getExpenses() is returning all expenses that have ever been entered into Splitwise even deleted ones. Can this be fixed? Or is there a way to eliminate deleted expenses from the list it returns?

**Comment by salehraghib** [comment]
Actually I found the getDeletedBy() and getDeletedAt() methods which might help in identifying deleted expenses. But, is it possible to add a parameter that doesn't return deleted expenses?

**Comment by namaggarwal** [comment]
Thanks. Do you want to submit a pull request for this?

**Comment by namaggarwal** [comment]
Splitwise does not provide a way to do this. Till then please use getDeletedBy and getDeletedAt
