### ISSUE TITLE
getExpenses crashes

### ISSUE THREAD

**Issue by sloppycoffee** [namaggarwal/splitwise#2]
I might be doing something wrong but the getExpenses call crashes.

The call:        sObj.getExpenses()

The output:
  File "/usr/local/lib/python3.4/dist-packages/splitwise/**init**.py", line 189, in getExpenses
    for param in params:
RuntimeError: dictionary changed size during iteration

**Comment by namaggarwal** [comment]
Hi,

Was it working before ?

**Comment by sloppycoffee** [comment]
I don't think I have ever seen that function work before. Does it work on
your side? Might be on my side.

**Comment by namaggarwal** [comment]
Hi,

It does work on my side. I haven't written the test cases (which I really should) to make it easy to test on different versions of Python. I will have a look at it this weekend.

Will keep you posted.

**Comment by sloppycoffee** [comment]
Thanks.

**Comment by sloppycoffee** [comment]
What version of python were you using to get it to work? I am on 3.4.3.

**Comment by sloppycoffee** [comment]
http://stackoverflow.com/questions/11941817/how-to-avoid-runtimeerror-dictionary-changed-size-during-iteration-error

Is this the issue?

**Comment by namaggarwal** [comment]
Hi,

My day job is keeping me busy. I will test it tomorrow and let you know :)

**Comment by sloppycoffee** [comment]
Excellent! I only need two functions for my project. Getexpense being one.

**Comment by namaggarwal** [comment]
Hi,

I found the bug. The bug is that I manage options passed to getExpenses from locals() and later adding more things to local variables modifies that list causing the error. I will fix this by copying the locals() into a separate variable and then using that.

**Comment by namaggarwal** [comment]
I have pushed a new release on pypi that should fix this. Please upgrade to the latest version and let me know if any issue :)

**Comment by sloppycoffee** [comment]
Excellent! Will do!

**Comment by sloppycoffee** [comment]
Your changes worked flawlessly. I got everything up and running. How
difficult is it to create a new function for create_expense? I saw you
didn't implement any of the POST API call but figured you could whip up the
function faster than I can. If not, can you point me to the area that I
should start on implementing that call?
http://dev.splitwise.com/dokuwiki/doku.php?id=create_expense

**Comment by sloppycoffee** [comment]
Hold up.. Ill do the easy stuff and see if I can get it.. Looking through
your code.. Looks pretty well organized.. Not really sure what the classes
in the other files (not **init**.py), are used for. So far I can make set
the new def for createExpense in **init**.py and send it over if I get
stuck.

**Comment by namaggarwal** [comment]
It should not be difficult to create a create_expense call. Basically you need to create a new function for createExpense and a common function to implement POST requests in **init**.py You can create a new class as well to hold the POJO objects. Let me know if you have difficulty, I can implement that for you.

**Comment by sloppycoffee** [comment]
Actually, I am having trouble. I first tried conforming to your previous
functions by setting up something like this:
 def __makePostRequest(self,url,body):

```
    resp, content = self.client.request(url, data=json.dumps(body))

    if Splitwise.isDebug():
        print(resp, content)

    #Check if the response is correct
    if resp['status'] != '200':
        raise Exception("Invalid response %s. Please check your
```

consumer key and secret." % resp['status'])

```
    return content
```

This was called from this:
 url = Splitwise.CREATE_EXPENSE_URL
content = self.__makePostRequest(url,options)
content = json.loads(content.decode("utf-8"))
print (content)

But I am pretty sure self.client.request only takes two args, url and
"POST". Not sure how to include a payload with that..

I then reverted to misc stackoverflow post methods, mostly by using httplib
or request. I seemed to get it to post but then it returned, authorization
failed or something similar. If you wouldn't mind explaining how to get
this all hooked up, that would be great.

P.S I prob should show my little tester code for create_expense too. The
first arg is "payment" which I don't really know what should be used
there.. I don't think it is the title.

expensesTest =
sObj.createExpense(payment="Testing1",cost="19.00",description="This is a
test description",group_id="#######")

  def
createExpense(self,payment=None,cost=None,description=None,group_id=None,friendship_id=None,details=None,creation_method=None,date=None,
            repeat_interval=None,currency_code=None,Category_id=None):
        # I am pulling this down.. Not sure if I need to...
        options = {}

```
    #Copy of the locals is created as if I directly work on
    #locals and create variables in the loop a dictionary changed
    #error is thrown. Refer to bug #2 on Github
    localCopy = dict(locals())
    params = localCopy.keys()
    for param in params:
        if param != 'self' and param != 'options' and
```

localCopy.get(param) is not None:
                options[param] = localCopy.get(param)

```
    url = Splitwise.CREATE_EXPENSE_URL
```

**Comment by namaggarwal** [comment]
So I have created a new issue for this

https://github.com/namaggarwal/splitwise/issues/4

Post your comments related to this on the link and I will have a look as soon as I get time. 

From what I can see you are not creating a POST request. I will look in detail later
