### ISSUE TITLE
getExpenses() retrieves only 20 expenses from Splitwise

### ISSUE THREAD

**Issue by DarynaDziuba** [namaggarwal/splitwise#20]
Hello!
There is an issue that the following code:
expenses = sObj.getExpenses()
returns the list of 20 objects only. However, there are more expenses by the user.
Please advise how to get all the expenses from the Splitwise.
Thanks!

BR

**Comment by namaggarwal** [comment]
Hi,

getExpenses take a parameter called limit. You can set it to 0 to get all the expenses.

```
sObj.getExpenses(limit=0)
```
