### ISSUE TITLE
sObj.getAuthorizeURL() does not return oauth_verifier

### ISSUE THREAD

**Issue by vishalseshagiri** [namaggarwal/splitwise#21]
My URL looks something like this 
```https://secure.splitwise.com/authorize?oauth_token=####################```

**Comment by namaggarwal** [comment]
You need to redirect your user to this URL, which will present a login page. After that it will redirect to your application and will give you oauth_verifier

**Comment by yashbhutoria** [comment]
As per my need, this will run on a serverless function under automation. How do I get oauth_verifier in that case?

**Comment by namaggarwal** [comment]
You would need to get a token first and hardcode that in your automation code. Its 3 legged OAuth so it requires user's authentication
