### ISSUE TITLE
Create Expense is not getting reflected

### ISSUE THREAD

**Issue by mvsreejithfrnds** [namaggarwal/splitwise#25]
I could post the create expense request successfully but not reflected in Spiitwise

Expense create completed without error but not reflected in Splitwise
OAuth: Oauth 1.0
Api: create_expense
Request (Body parameters)
users__0__owed_share : 75.0
cost : 150.0
users__1__owed_share : 75.0
users__1__user_id : my user id
users__0__paid_share : 0.0
description : "test"
payment : false
users__1__paid_share : 150.0
users__0__user_id : friend user id

Response
Response{code=200, message='OK', body='null', headers={Transfer-Encoding=chunked, null=HTTP/1.1 200 OK, Server=nginx, X-Request-Id=2915a687-0d9b-4e6e-a9f0-18bf835d1dd5, X-Runtime=0.037593, X-Content-Type-Options=nosniff, Connection=keep-alive, Pragma=no-cache, Date=Fri, 03 Jan 2020 23:32:03 GMT, Via=1.1 vegur, Referrer-Policy=origin, X-Frame-Options=SAMEORIGIN, Strict-Transport-Security=max-age=31536000, Cache-Control=no-cache, no-store, max-age=0, must-revalidate, Content-Disposition=inline; filename="response.json", X-Xss-Protection=1; mode=block, Set-Cookie=, Vary=Accept-Encoding, Expires=Fri, 01 Jan 1990 00:00:00 GMT, Content-Type=application/json; charset=utf-8}}

**Comment by krnbatra** [comment]
I'm also not able to createExpense. It displays the following error. I'm using the same example as listed in the README:

File "/usr/local/lib/python3.7/site-packages/splitwise/__init__.py", line 251, in createExpense
    expense = Expense(content["expenses"][0])
IndexError: list index out of range

**Comment by krnbatra** [comment]
> I'm also not able to createExpense. It displays the following error. I'm using the same example as listed in the README:
> 
> File "/usr/local/lib/python3.7/site-packages/splitwise/**init**.py", line 251, in createExpense
> expense = Expense(content["expenses"][0])
> IndexError: list index out of range

my bad, working fine now.

**Comment by namaggarwal** [comment]
@mvsreejithfrnds Can you confirm its still not reflected. I am planning to work on issues this weekend
