### ISSUE TITLE
Existing expenses with Deleted Group: 404 Error

### ISSUE THREAD

**Issue by MarcelloMolinaro** [namaggarwal/splitwise#27]
I do not think that this is an issue with your package, but it may be. I'm wondering if anyone else has come across this: 
I can pull expense objects [via getExpenses()] that have a deleted group. The id, however, still is listed. So when I try to lookup the group name [via sObj.getGroup(expense.getGroupId()).getName()] I get an error.

Any thoughts?

From the API Documentation site:
>delete_group/:id
>Example Response:
>POST https://secure.splitwise.com/api/v3.0/delete_group/:id
>Delete an existing group. Destroys all associated records (expenses, etc.)

P.S. Thank you for building this package!

**Comment by namaggarwal** [comment]
Thank you so much for the appreciation. That what keeps me going. 

Yes you are right. Splitwise returns the GroupID even when the group is deleted. Library doesn't handle errors very well at the moment. I will try and fix that
