### ISSUE TITLE
Shall I create a merge request for the undocumented export_friend API?

### ISSUE THREAD

**Issue by siebert** [namaggarwal/splitwise#63]
I'm using the splitwise Python API to call the export_friend API periodically via cron, which triggers an export of all expenses as a .csv file and sends via eMail.

The functionality is available via the Web interface of Splitwise, but the API seems to be undocumented. I would like to create a merge request with a new method to call export_friend, but I don't know if undocumented APIs are accepted.

**Comment by siebert** [comment]
No response, so I close this issue.

**Comment by namaggarwal** [comment]
Hello @siebert Apologies for no reply. My day job is keeping me too busy. Undocumented API shouldn't be part of this SDK as they list this on their website. Thank you
