### ISSUE TITLE
pip Version 2.3 does not include UpdateExpense

### ISSUE THREAD

**Issue by lorcan17** [namaggarwal/splitwise#72]
`Traceback (most recent call last):
  File "src/update_expenses.py", line 87, in <module>
    s.updateExpense(expense)
AttributeError: 'Splitwise' object has no attribute 'updateExpense'
Error: Process completed with exit code 1.`

Here's my pip code:
`Collecting splitwise==2.3.0
  Using cached splitwise-2.3.0-py3-none-any.whl (50 kB)
 `

Can you update the version on pip?

**Comment by lorcan17** [comment]
I'm able to run my script by using pulling the source code from this repo so the issue is definately with the pip version

**Comment by namaggarwal** [comment]
Testing this functionality and will be releasing soon

**Comment by namaggarwal** [comment]
Released version 2.4.0
